# Generated by Django 5.1.4 on 2024-12-06 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_initial'),
        ('seekers', '0001_initial'),
        ('vacancies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='seekers.userprofile'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='abilities',
            field=models.ManyToManyField(blank=True, related_name='work_experience', to='seekers.ability'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.position'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='references', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to='seekers.userprofile'),
        ),
    ]
