# Generated by Django 5.1.4 on 2024-12-08 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seekers', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='applied_vacancies',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bookmarked_vacancies',
        ),
    ]
