# Generated by Django 5.1.4 on 2024-12-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekers', '0003_remove_userprofile_applied_vacancies_and_more'),
        ('vacancies', '0003_remove_vacancy_bookmarked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bookmarked_vacancies',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_users', to='vacancies.vacancy'),
        ),
    ]
