# Generated by Django 5.1.4 on 2024-12-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekers', '0004_userprofile_bookmarked_vacancies'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
