# Generated by Django 5.1.1 on 2024-10-22 18:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vacancies', '0002_remove_hiddenvacancies_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.CharField(max_length=255)),
                ('experience_years', models.IntegerField()),
                ('proficiency_level', models.CharField(choices=[('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior'), ('expert', 'Expert')], default='junior', max_length=20)),
            ],
            options={
                'ordering': ['technology'],
                'unique_together': {('technology', 'experience_years', 'proficiency_level')},
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.vacancy')),
            ],
            options={
                'ordering': ['-applied_on'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('links', models.TextField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('abilities', models.ManyToManyField(blank=True, related_name='users', to='user_profile.ability')),
                ('applied_vacancies', models.ManyToManyField(blank=True, related_name='applicants', to='user_profile.application')),
                ('bookmarked_vacancies', models.ManyToManyField(blank=True, related_name='bookmarked_by', to='vacancies.vacancy')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='user_profile.userprofile'),
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('abilities', models.ManyToManyField(blank=True, related_name='work_experience', to='user_profile.ability')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.company')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.position')),
                ('reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='references', to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to='user_profile.userprofile')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
