# Generated by Django 5.1.1 on 2024-10-22 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
        ('vacancies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='user_profile.userprofile'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='abilities',
            field=models.ManyToManyField(blank=True, related_name='work_experience', to='user_profile.ability'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.company'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.position'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='references', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to='user_profile.userprofile'),
        ),
    ]
