# Generated by Django 5.1.4 on 2024-12-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referenceletter',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
