# Generated by Django 5.1.4 on 2024-12-08 12:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='applications',
            field=models.ManyToManyField(blank=True, related_name='applied_vacancies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='bookmarked_by',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_vacancies', to=settings.AUTH_USER_MODEL),
        ),
    ]
