# Generated by Django 5.1.4 on 2024-12-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_remove_vacancy_bookmarked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
